### ISSUE TITLE
Feature requested: addBarsFromDataFrame

### ISSUE THREAD

**Issue by tesla1060** [gbeced/pyalgotrade#12]
Hi, 

For example, I have a DataFrame what contains 1000 rows of ohlcv data. And now I want to use N1 rows for training, and N2 rows for back testing.N1+N2 = 1000. I dont want N1 goes into feed, because, that will mean I have traverse each bar for training. I only want N2 to go into feed, but that mean I have to form a csv file of N2 rows in order to use addBarsFromCSV .
If I change the (N1, N2) combination a lot, this can be really dreadful. Is there a nice way to form the feed using a in memory datastructure, say a pandas DataFrame?

**Comment by gbeced** [comment]
I don't think there is a standard dataframe format for OHLCV data. The name of the columns may vary, the datetime may be part of the index or a separate column, etc.
In order to fulfil your request I'd need to build something that accepts a dataframe along with information on how to pull the different values out of the dataframe to build bar objects.

I'm not going to do so in the short term. A workaround would be to save the dataframe in CSV format and load it using http://gbeced.github.io/pyalgotrade/docs/v0.16/html/barfeed.html#pyalgotrade.barfeed.csvfeed.GenericBarFeed or you can build your own BarFeed that wraps your specific dataframe.

**Comment by femtotrader** [comment]
See
http://pandas.pydata.org/pandas-docs/stable/remote_data.html
Most DataReader returns OHLCV data as DataFrame with column name 'Open', 'High', 'Low', 'Close', 'Volume' .
(it can also be a Panel if you pass several symbol in a list)
(you might be interested by http://pandas-datareaders.readthedocs.org/ )

You could consider passing a DataFrame with column name 'Open', 'High', 'Low', 'Close', 'Volume' and an optional parameter (dict with column name if DataFrame doesn't have "standard" column name)

if a DataFrame uses upper case column name. You can rename columns using:

    d_cols= {'OPEN': 'Open', 'HIGH': 'High', 'LOW': 'Low', 'CLOSE': 'Close'}
    df = df.rename(columns=d_cols)

**Comment by gbeced** [comment]
This may be useful: https://groups.google.com/forum/#!topic/pyalgotrade/lyCerE3eE-E

**Comment by femtotrader** [comment]
Thanks. What is interesting with DataFrame (or Panel) feed is that it will allow to easily feed OHLCV data:

 - from Excel http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_excel.html
 - from SQL database http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql.html
 - from HDF5 http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_hdf.html

see http://pandas.pydata.org/pandas-docs/stable/io.html

A panel feed will be interesting too but dimensions order matters
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Panel.transpose.html

**Comment by femtotrader** [comment]
Caution:

    from pandas.io import data, wb

will be deprecated. It becomes

    from pandas_datareader import data, wb

`pandas_datareader` need to be install using

    $ pip install pandas-datareader
