### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by femtotrader** [gbeced/pyalgotrade#43]
Hello,

You should add continuous integration builds using Travis.
That's very easy and free for open source projects.

You just need a `.travis.yml` file

I have 2 projects using it:

https://github.com/femtotrader/pandas_datareaders

https://github.com/femtotrader/ig-markets-rest-api-python-library

Kind regards

**Comment by gbeced** [comment]
I'm working on it but there are some limitations:
* **optimizer_testcase** is disabled because it gets blocked in Travis. Need to further anylyze.
* **twitter_test** is disabled because it requires credentials.
* **talib_test** is disabled until I get it to work on Travis.
* **bitstamp_test** is disabled until Bitstamp gets back online.

**Comment by gbeced** [comment]
https://travis-ci.org/gbeced/pyalgotrade

**Comment by femtotrader** [comment]
Credentials is not a problem. You need to pass credentials using environment variables (`os.environ`)
and you can define these environment variables as "secret"
see http://stackoverflow.com/questions/9338428/using-secret-api-keys-on-travis-ci
you can also define environment variables using web interface (not only CLI)

**Comment by femtotrader** [comment]
Thanks
